FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# Copy the pom.xml and project files
COPY ./pom.xml .
COPY ./src ./src

# Package the application
RUN mvn clean package -DskipTests

# Use the official OpenJDK image to run the app
FROM openjdk:17-jdk-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR de tu aplicación al contenedor
COPY --from=build /app/target/eureka-prueba-espublico.jar /app/app.jar

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8090

# Ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]