spring:
  cloud:
    gateway:
      routes:
      - id: documentos
        uri: lb://documento
        predicates:
            - Path=/api/documentos/**
        filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,routes,gateway
  endpoint:
    health:
      show-details: always